### PR TITLE
Issue 252

### PR DESCRIPTION
**Pull request by mjordan**

### CODE REVIEW

**Comment by mjordan** [comment]
I'll resolve these tests. Tagging @bondjimbond to let him know status.

**Comment by mjordan** [comment]
I'm in waaay over my head here gitwise. I'd like to delete this branch and cut a new one from master, which has moved along somewhat since I originally cut this branch. The new one will contain the manipulator file and a single test method and should not have any conflicts. @MarcusBarnes any objections?

**Comment by MarcusBarnes** [comment]
@mjordan No objections.  Please do what you feel will help move things along well.  Thank you.

**Comment by mjordan** [comment]
OK, thanks, will attempt now.

**Pull request closed without merging**
