### PR TITLE
Work on issue 434.

### PR DESCRIPTION
**Pull request by mjordan**
**Github issue**: (#434)

# What does this Pull Request do?

Adds links to some collections from the The Louisiana Digital Library migrated using MIK to the main README.md file.

# How should this be tested?

n/a

# Interested parties

@MarcusBarnes @jpeak5 @flummingbird

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
@jpeak5 @flummingbird If you would please review the LSU mentions, that would be appreciated.  (Thumbs up or down would work well.)  I'm OK with merging this since Travis CI passed.   We can review the codecov/project failure separately.  Thanks @mjordan for the PR.

**Comment by mjordan** [comment]
Sorry @MarcusBarnes I didn't know a simple change to a README would trigger a codecov failure. 😞

**Comment by mjordan** [comment]
@jpeak5 you have any problem with us merging this?

**Comment by jpeak5** [comment]
@mjordan looks great, thx!

**Pull request merged**
