### PR TITLE
Document the ignore_null_mappings parameter.

### PR DESCRIPTION
**Pull request by bondjimbond**
# What does this Pull Request do?

Adds a note about --ignore_null_mappings to README to avoid a very common source of confusion.

@mjordan @MarcusBarnes

### CODE REVIEW

**Comment by mjordan** [comment]
Sounds good. We should also add this note to https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Check-your-MIK-configuration-values.

**Comment by bondjimbond** [comment]
I did that probably as you were typing this comment!

**Comment by bondjimbond** [comment]
Is this mergeable?

**Comment by mjordan** [comment]
Yes, I'll go ahead. Thanks for adding this.

**Pull request merged**
