### PR TITLE
Remove undefined variable

### PR DESCRIPTION
**Pull request by whikloj**
**Github issue**: https://github.com/MarcusBarnes/mik/issues/401

# What does this Pull Request do?

Remove undefined variables

### CODE REVIEW

**Comment by mjordan** [comment]
Copy pasta FTW! Thanks for catching these @whikloj.

We've recently adopted a new workflow where we indicate in the PR if the change is testable or requires a smoketest. Details are laid out in our CONTRIBUTING.md.

Want you name added to the main README under "Contributors"? It's a pretty illustrious group!

**Comment by mjordan** [comment]
Tested with no side effects.

**Comment by mjordan** [comment]
Tested with no side effects. Thanks again @whikloj.

**Comment by whikloj** [comment]
Sorry about that @mjordan, I perused the PR template but I'll have to go in and really read the CONTRIBUTING.md. Thanks.

**Comment by mjordan** [comment]
No problem. We would appreciate any feedback on the CONTRIBUTING.md you might have.

**Pull request merged**
