### PR TITLE
Work on #436.

### PR DESCRIPTION
**Pull request by mjordan**
**Github issue**: (#436)

# What does this Pull Request do?

Escapes a regex pattern so that it doesn't fail on Windows.

# What's new?

As explained in the issue, adds the line `$directory_regex = preg_quote($directory_regex);` to the CsvNewspapers filegetter so the the DIRECTORY_SEPARATOR on Windows (`\`) is escaped properly.

# How should this be tested?

This change can only be tested thoroughly on Windows, but I used it yesterday to successfully generate a batch on Windows. On non-windows platforms, the fix should be invisible. To test this:

1. unzip the attached file, which contains some sample data and config files.
1. adjust values in the .ini to match your system.
1. in the master branch, run `./mik -c issue_436.ini`
1. change the name of the output directory so it is not overwritten in the next step
1. switch to the issue-436 branch and rerun `./mik -c issue_436.ini`
1. the output from the two branches should be identical (apart from timestamps in log files)

Results of PHP tests should also be the same across the master and issue-436 branches. In the mik directory, run:

`phpunit`

[issue_436.zip](https://github.com/MarcusBarnes/mik/files/1322268/issue_436.zip)

### CODE REVIEW

**Comment by mjordan** [comment]
I wonder if we should be doing a thorough audit of all uses of DIRECTORY_SEPARATOR and regexes and add the `preg_quote()` if it's not there.

**Comment by MarcusBarnes** [comment]
@mjordan That's a good idea.

**Comment by mjordan** [comment]
Or for that matter, creating our own wrapper function, where we could do everything in one place.

**Comment by mjordan** [comment]
@MarcusBarnes @bondjimbond tests run clean - can one of you merge this? Or I can do it myself if there are no objections.

**Comment by MarcusBarnes** [comment]
Thank you @mjordan.

**Comment by mjordan** [comment]
@MarcusBarnes thanks!

**Pull request merged**
