### PR TITLE
Uses [SYSTEM][date_default_timezone] to be set in the configuraiton f…

### PR DESCRIPTION
**Pull request by MarcusBarnes**
Addresses https://github.com/MarcusBarnes/mik/issues/215.

The expected behavior is to use [SYSTEM][date_default_timezone] if it is set in the config or use the value from the PHP.ini.  If date.timezone is not set in the PHP.ini and no [SYSTEM][date_default_timezone] is set in the MIK configuration file for the given collection, default to 'America/Vancouver'.

### CODE REVIEW

**Comment by mjordan** [comment]
@MarcusBarnes I tested this by setting the following in my .ini:

```
[SYSTEM]
date_default_timezone = 'America/Halifax'
```

But the timestamps in the mik log are accurate for me, they don't reflect Halifax time. Is that expected? If so, how do I know the .ini setting is the one being used?

**Comment by MarcusBarnes** [comment]
@mjordan I've reviewed the logic and the documentation for the date_default_timezone_set function.  Remember that setting this was so that monolog would work since it creates an error if date.timezone is not set. Most folks running this will have date.timezone set in their php.ini file.    If you add a check to output the result of date_default_timezone_get() around line 82 of MIK, that should show whether America/Halifax has been set properly.  This could be an issue with monolog not using the value set using date_default_timezone_set consistently (but rather defaults to using that present in the php.ini file if it's present).  I'll have to investigate some more.

**Comment by MarcusBarnes** [comment]
Shall we close this pull request until we've determined why you're still getting Vancouver timestamps when you've set the default timezone to another timezone in the main MIK script?

**Comment by mjordan** [comment]
No, let's continue to work on it. If it works for you then I'm probably testing it wrong.

**Comment by MarcusBarnes** [comment]
@mjordan Let me check some more cases - it's possible what you're seeing is because of a different environment.  My default php.ini does not have the date.timezone set.

**Comment by MarcusBarnes** [comment]
@mjordan When you have a moment, please test again.  If it works as expected, please feel free to merge the pull-request.

**Comment by mjordan** [comment]
Works as expected, merging.

**Pull request merged**
