### PR TITLE
Work on #310.

### PR DESCRIPTION
**Pull request by mjordan**
**Github issue**: https://github.com/MarcusBarnes/mik/issues/310

# What does this Pull Request do?

Adds a .gitattributes file containing directives on how to define line endings.

# What's new?

The addition of the .gitattributes file. Plus, as per discussion in PR, it removes the PHPUnit test that determines if FITS is configured properly.

# How should this be tested?

Checking out the issue-310 branch on Windows, Mac, and Linux should show the line ending of all files to be CRLF, LF, and LF respectively.

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
@mjordan The Travis CI build failed.   We'll have to investigate why the .gitattributes file is making the Travis CI build fail.  Thanks.

**Comment by mjordan** [comment]
I'll look into it.

**Comment by mjordan** [comment]
@MarcusBarnes I have no idea why that test is failing (it shouldn't even be run). It's kind of a peculiar test anyway, since it tests a system-level configuration external to MIK, run within a post-write hook script. Any objections to removing it all together?

**Comment by MarcusBarnes** [comment]
@mjordan No objections to removing that test since, as you point out, it's a "system-level configuration external to MIK, run within a post-write hook script."  Thank you.

**Comment by mjordan** [comment]
OK, thanks. I'll remove it.

**Comment by MarcusBarnes** [comment]
@mjordan Any other pending changes on your end before I merge?

**Comment by mjordan** [comment]
None!

**Pull request merged**
