### PR TITLE
Issue 226

### PR DESCRIPTION
**Pull request by mjordan**
@MarcusBarnes please review the proposed CONTRIBUTING.md and pull request template. We may also want to name ourselves in the "Maintainers/sponsors" section of README.md and also list all contributors in a "Contributors" section. Before merging, we should also consult with everyone who has already contributed so for to confirm that they will accept the requirements detailed in the new "license agreements" section.

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
Reviewed.   I'm satisfied with CONTRIBUTING.md.  Thank you for putting it together following our discussions.

**Comment by mjordan** [comment]
Creation of the issue-226 branch predates the addition of travis.yml in #272. I can merge master into issue-226 and all tests should pass. @MarcusBarnes any objections?

**Comment by MarcusBarnes** [comment]
No objections.

**Comment by mjordan** [comment]
OK, will wait to hear back from Brian, then tag individual contributors to get their signoff. Once that's all don, will update this branch and give you the OK to merge.

**Comment by mjordan** [comment]
@MarcusBarnes Brian sees no problem with the proposed language. I'll merge master into this branch to resolve the travis error and post here tagging our existing contributors.

**Comment by mjordan** [comment]
@jpeak5 @flummingbird @mark-cooper @patdunlavey @bondjimbond  This PR adds a CONTRIBUTING.md and in it, we are including language about transferring ownership of code contributions to the MIK maintainers for the sole purpose of redistributing the contributed code with the rest of the MIK codebase under the terms of the GPL3. This transfer is non-exclusive, so you still own the code, you're just givinig MIK a copy of it for inclusion in the MIK codebase.

Our motivation for asking that contributors transfer ownership of their code contributions to the MIK maintainers (whoever they are at the time of the contribution) is to avoid situations in the future where ownership of specific code becomes difficult or impossible to determine, for example after multiple subsequent changes to the contributed code by the maintainers or other contributors.

The relevant section of the CONTRIBUTING.md added in this PR is on [line 74](https://github.com/MarcusBarnes/mik/pull/306/files#diff-6a3371457528722a734f3c51d9238c13R74). The language asks that you transfer ownership of your contributed code to the MIK maintainers rather than (to use the language from the Islandora Contributor License Agreement) "a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license" to redistribute the code.

We will acknowledge all contributors to MIK on the main README.md file.

We'd like to ask each of you to accept the proposed license retroactively before we merge this PR. If you do accept the proposed license, you can indicate it here in the comments for this PR or if you would rather, email me at mjordan at sfu ca. If you have any comments on the proposed license or cannot accept it, also leave comments here or email me.

Thank you for your contributions to MIK!

**Comment by bondjimbond** [comment]
Fine by me.

**Comment by patdunlavey** [comment]
No problem.

**Comment by jpeak5** [comment]
Fine by me

Sent from my iPhone

On Nov 29, 2016, at 10:17 AM, Mark Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


@jpeak5<https://github.com/jpeak5> @flummingbird<https://github.com/flummingbird> @mark-cooper<https://github.com/mark-cooper> @patdunlavey<https://github.com/patdunlavey> @bondjimbond<https://github.com/bondjimbond> This PR adds a CONTRIBUTING.md and in it, we are including language about transferring ownership of code contributions to the MIK maintainers for the sole purpose of redistributing the contributed code with the rest of the MIK codebase under the terms of the GPL3. This transfer is non-exclusive, so you still own the code, you're just givinig MIK a copy of it for inclusion in the MIK codebase.

Our motivation for asking that contributors transfer ownership of their code contributions to the MIK maintainers (whoever they are at the time of the contribution) is to avoid situations in the future where ownership of specific code becomes difficult or impossible to determine, for example after multiple subsequent changes to the contributed code by the maintainers or other contributors.

The relevant section of the CONTRIBUTING.md added in this PR is on line 74<https://github.com/MarcusBarnes/mik/pull/306/files#diff-6a3371457528722a734f3c51d9238c13R74>. The language asks that you transfer ownership of your contributed code to the MIK maintainers rather than (to use the language from the Islandora Contributor License Agreement) "a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license" to redistribute the code.

We will acknowledge all contributors to MIK on the main README.md file.

We'd like to ask each of you to accept the proposed license retroactively before we merge this PR. If you do accept the proposed license, you can indicate it here in the comments for this PR or if you would rather, email me at mjordan at sfu ca. If you have any comments on the proposed license or cannot accept it, also leave comments here or email me.

Thank you for your contributions to MIK!

-

**Comment by flummingbird** [comment]
fine.

-Will

**Comment by mark-cooper** [comment]
:+1:

**Comment by mjordan** [comment]
W00t! Thanks everyone. @MarcusBarnes unless there are any further considerations, please merge at your convenience.

**Comment by MarcusBarnes** [comment]
Thank you everyone for your contributions.

**Comment by mjordan** [comment]
@MarcusBarnes do you want me to update the main README.md to refer to the new CONTRIBUTING.md and to list all contributors so far?

**Comment by MarcusBarnes** [comment]
@mjordan That would be awesome.  Thank you.

**Comment by mjordan** [comment]
OK, I'll do that, OK to push directly to master with no PR?

**Comment by MarcusBarnes** [comment]
Yes - that's OK.  Thank you.

**Pull request merged**
