### PR TITLE
Issue 240

### PR DESCRIPTION
**Pull request by mjordan**
**Github issue**: https://github.com/MarcusBarnes/mik/issues/240

# What does this Pull Request do?

Adds input validators, as described in #240, for CSV Single File, CSV Newspapers, Csv Compound, and Csv Books toolchains

# What's new?

* added working input validators for CSV Single File, CSV Newspapers, Csv Books, and Csv Compound toolchains
* modified mik to integrate the validators in 'strict' mode
* modified the writers for those three toolchains to integrate the validators in 'realtime' mode
* added PHPUnit tests and test assets for all four input validators
* modified .travis.yml to run the tests on these input validators separately from the other PHPUnit tests

# How should this be tested?

## PHPUnit tests

Running `phpunit --group inputvalidators --bootstrap vendor/autoload.php tests` in the MIK directory will run tests for all four input validators.

## Manual tests

* For all four toolchains, adding `validate_input = false` to the .ini file's `[FILE_GETTER]` section will disable the input validators. MIK's behavior will be the the same as it was before the addition of the code in this PR.
* For all four toolchains, adding `validate_input_type = strict` to the .ini file's `[FILE_GETTER]` section will cause MIK to validate the input packages and not generate any output. In other words, with this configuration setting, running `./mik -c foo.ini` will not produce any Islandora ingest packages. All it will produce is a log (as defined in detailing any validation errors. The validation log's path is defined in the optional ['LOGGING']['path_to_input_validator_log'] .in setting; default location is input_validator.log in the MIK output directory.
* For all toolchains, adding `validate_input_type = realtime` (the default; will be in effect if no configuration option is provided) to the .ini file's `[FILE_GETTER]' section will cause MIK to validate the input packages as they are being generated. If a package fails any input validation test, its generation will be skipped and its ID will be added to the problem.log. All validation failures will be detailed in the input validator log.
* Toolchain-specific tests:
  * CSV single file
    * The only check we make is that the file named in the CSV record's file_name_field exists
  * CSV compound
    * Compound object-level directory named in the CSV record's compound_directory_field must exist, and be a directory
    * Compund object-level directory cannot contain 'Thumbs.db', '.Thumbs.db', 'DS_Store', or '.DS_Store'
    * Compound object-level directory must contain at least n files, where n is defined in $settings['WRITER']['min_children']; (as per #291). Default is 2 files.
    * Files in compound object-level directory must be named such that their last filename segment is numeric.
  * CSV newspapers
    * Issue-level directory named in the CSV record's file_name_field must exist and be named using the yyyy-mm-dd pattern.
    * Issue-level directory must contain at least one page file.
    * The page filenames must be names such that their page sequence numbers are numeric.
  * CSV books
    * Book-level directory named in the CSV record's file_name_field must exist, and be a directory.
    * The book-level directory cannot be empty.
    * The book-level directory cannot contain directory cannot contain 'Thumbs.db', '.Thumbs.db', 'DS_Store', or '.DS_Store'.
    * Files in the book-level directory must have one of the allowed extensions ('tiff', 'tif', or 'jp2'.).
    * Files in the book-level directory must be named such that their page sequence numbers are numeric.

Given that there are PHPUnit tests, I think it's OK to do a manual smoke test to see if the configuration options work the way you expect, using the CSV single file toolchain.

There is one issue that I cannot figure out, but that is harmless: in 'realtime' mode, the "Initializing log" entry shows up twice in input_validator.log. I can open a separate issue for this later.

### CODE REVIEW

**Comment by mjordan** [comment]
Cookbook entry providing an overview of input validation is at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Validate-MIK's-input-files. Once this is merged, I'll update each of the CSV toolchain pages to document the .ini options and to point to this page.

**Comment by mjordan** [comment]
@MarcusBarnes I'm sorry, I just found a problem. If you run mik on non-CSV toolchains, you get an fatal error. I can fix this, and possibly the double-initialization issue I mention above, before you merge.

**Comment by mjordan** [comment]
OK, problem with running mik with non-CSV toolchains fixed, as well as the double-initialization I mentioned.

**Comment by MarcusBarnes** [comment]
A quick report on my testing progress for this pull request.  The PHPUnit command passes successfully.  The manual testing of the CSV books works as expected for the five different cases listed in the bullet points, when `validate_input_type` is set to `strict` and when it is set to`realtime`.

**Comment by mjordan** [comment]
@MarcusBarnes noticed you just merged this - thanks! Can you take a look at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Validate-MIK's-input-files to see if it is consistent with your understanding of how this works? If it is, I'll link it from the wiki table of contents.

I'll also need to update the various CSV toolchain wiki pages to describe the new config options.

**Comment by MarcusBarnes** [comment]
@mjordan  Thank you.  I'll double check https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Validate-MIK's-input-files and report should I find anything that seems inconsistent with my understanding of how they work.

**Comment by MarcusBarnes** [comment]
@mjordan  What is described in https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Validate-MIK's-input-files is consistent with my understanding on how the input validation works (for the four currently supported Csv workflows).

**Comment by mjordan** [comment]
Super, thanks, I'll finish documentation today.

**Comment by mjordan** [comment]
OK, all CSV toolchain wiki entries updated, and I've linked the cookbook entry from the cookbook table of contents.

**Pull request merged**
